### PR TITLE
Revert "Add processing modules after PEP updates & test_rixs.py"

### PR DESCRIPTION
**Pull request by awalter-bnl**
Reverts scikit-beam/rixs#4

I want to revert these changes as there is a lot still to work through before they are ready to merge, and I haven't been given enough time to check through the code myself yet.

### CODE REVIEW

**Comment by awalter-bnl** [comment]
I have added some comments to PR #4 that I would like to see changed

**Comment by mpmdean** [comment]
I think this addresses the points as best I can in the new commit. 

I am keen to be able to share the code and have Andi, Valentina, etc. start running it on real data. We have an experiment in only one week and if we don't have something shared between us, we will each be separately trying to hack together different bits of code.

**Comment by awalter-bnl** [comment]
I will take a look at this early next week when I have the chance, as this is the first full PR to scikit-beam/rixs I would also like feed back from @danielballan and/or @tacaswell . I have requested a review from them.

As mentioned in the meeting earlier this week, having this stuff ready for this cycle is unrealistic. Having it ready for later this week is really not possible given my schedule. If you would like others to use it before it is merged they can fork your branch (or the revert-4-master branch if you didn't create your own fork) prior to this being merged into the master branch.

**Comment by awalter-bnl** [comment]
I just realized that there are no commits to this PR and the only other open PR is my initial one. @mpmdean can you please merge this PR and open a new PR with the changed files in it as this will make it easier for others to follow.

**Comment by danielballan** [comment]
I would like to add that looking at the overall quality of this code makes me _very_ happy: well-formatted docstrings, at least _some_ tests, generally well-factored function signatures. This is off to a great start.

I think @awalter-bnl is right about process. It's good to go through revision before merging.

> If you would like others to use it before it is merged they can fork your branch (or the revert-4-master branch if you didn't create your own fork) prior to this being merged into the master branch.

If you need help with that let us know.

**Pull request merged**
