### PR TITLE
add a function to extract regions from a 2D image

### PR DESCRIPTION
**Pull request by awalter-bnl**
This commit adds a function <extract_regions> which extracts regions from a 2D array and returns a dictionary containing the regions as well as the arrays related to those regions.

### CODE REVIEW

**Comment by awalter-bnl** [comment]
FYI, I am waiting on the feedback, via basecamp, on weather this should be here or in NSLS-II-SIX/sixtools before removing the "Do not merge" tag.

**Comment by danielballan** [comment]
The return value of this function -- a dictionary with labels mapped to subarrays -- is not the most useful representation. It is more useful to pass around slices:

```py
regions = {1: [slice(1, 2), slice(3, 4)], 2: [slice(3, 6), slice(2, 4)]}
```

or so-called label arrays, which are a "paint by number" representation of this array:

```py
labels = np.zeros_like(arr)  # an array of zeros with the same dimensions as arr
for i, region.items()
    # Paint the subarray region with the number i.
    labels[region] = i
```

Then our label array `labels` looks like:

```py
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 2., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 2., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 2., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
```

Which of these is better depends on that context. Scikit-image provides tools for switching between them.

**Comment by danielballan** [comment]
Recommended reading: http://scikit-image.org/docs/dev/user_guide/numpy_images.html

**Comment by awalter-bnl** [comment]
This is a good point, and much better form a memory usage point of view. I am about to move this stuff to NSLS-II-SIX/sixtools but will make this change at the same time.

**Comment by awalter-bnl** [comment]
closing this as it is being moved to NSLS-II-SIX/sixtools

**Pull request closed without merging**
